site_name: JohnTrunix's Brain Cache
site_author: JohnTrunix
site_description: JohnTrunix's Brain Cache, my personal go-to hub for tech-savvy personal notes and insights

site_url: https://johntrunix.github.io/brain-cache/
repo_name: JohnTrunix/brain-cache
repo_url: https://github.com/JohnTrunix/brain-cache
remote_branch: gh-pages
edit_uri: edit/main/docs/

theme:
    name: material
    custom_dir: docs/.overrides
    language: en
    logo: custom/rocket.png
    favicon: custom/favicon.ico

    icon:
        repo: fontawesome/brands/github
        view: octicons/file-code-16

        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16

    font:
        text: Roboto
        code: Fira Code

    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-6
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-6
              name: Switch to light mode

    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        # - navigation.sections
        - navigation.expand
        - navigation.indexes
        - navigation.top
        - navigation.footer
        - search.suggest
        - search.share
        - content.action.view
        - content.action.edit
        - content.code.copy

extra_css:
    - custom/css/tweaks.css
    - custom/css/source_metadata.css
    - custom/css/pdf-cards.css

extra_javascript:
    - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
    - custom/js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/JohnTrunix/
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/john-truninger/
        - icon: simple/kofi
          link: https://ko-fi.com/johntrunix
    analytics:
        provider: google
        property: !ENV GOOGLE_ANALYTICS
        feedback:
            title: Was this page helpful?
            ratings:
                - icon: octicons/heart-16
                  name: This page was helpful
                  data: 1
                  note: >-
                      Thanks for your feedback!
                - icon: octicons/x-16
                  name: This page could be improved
                  data: 0
                  note: >-
                      Sorry to hear that. Can you give me some suggestions?

copyright: Copyright &copy; 2024 JohnTrunix

plugins:
    - social:
          cards: !ENV [CARDS, False]
    - tags
    - search:
          lang:
              - en
              - de
    - glightbox:
          loop: false
    - git-revision-date-localized:
          type: timeago
          enable_creation_date: true
          fallback_to_build_date: true
          enabled: !ENV [GIT_REVISION_DATE, False]
    - git-committers:
          repository: johntrunix/brain-cache
          branch: main
          enabled: !ENV [GIT_COMMITTERS, False]

markdown_extensions:
    - toc:
          permalink: true
    - attr_list
    - def_list
    - md_in_html
    - markdown.extensions.admonition
    - markdown.extensions.footnotes
    - markdown.extensions.toc:
          permalink: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.mark
    - pymdownx.details
    - pymdownx.keys

nav:
    - Overview:
          - index.md
          - Ideas & Upcoming Projects: overview/ideas-upcoming-projects.md
          - Links & Resources: overview/urls-resources.md

    - Genral Notes:
          - Git: general/git.md
          - LaTeX:
                - general/latex/index.md
                - Elements: general/latex/elements.md
                - Math: general/latex/math.md
                - Plots: general/latex/plots.md
          - Docker Topics:
                - Docker: general/docker/docker.md
                - Docker Compose: general/docker/docker-compose.md
          - Other:
                - Graphs: general/graphs.md
                - MkDocs Material: general/mkdocs-material.md

    - Python:
          - BuiltIn Modules:
                - coding/python/builtin/index.md
                - abc: coding/python/builtin/abc.md
                - argparse: coding/python/builtin/argparse.md
                #- asyncio: coding/python/builtin/asyncio.md
                #- base64: coding/python/builtin/base64.md
                #- cmath: coding/python/builtin/cmath.md
                #- collections: coding/python/builtin/collections.md
                #- dataclasses: coding/python/builtin/dataclasses.md
                - enum: coding/python/builtin/enum.md
                #- gc: coding/python/builtin/gc.md
                #- hashlib: coding/python/builtin/hashlib.md
                #- html: coding/python/builtin/html.md
                #- io: coding/python/builtin/io.md
                #- json: coding/python/builtin/json.md
                #- logging: coding/python/builtin/logging.md
                #- math: coding/python/builtin/math.md
                #- multiprocessing: coding/python/builtin/multiprocessing.md
                #- os: coding/python/builtin/os.md
                #- pathlib: coding/python/builtin/pathlib.md
                #- queue: coding/python/builtin/queue.md
                #- random: coding/python/builtin/random.md
                #- socket: coding/python/builtin/socket.md
                #- sys: coding/python/builtin/sys.md
                #- threading: coding/python/builtin/threading.md
                #- types: coding/python/builtin/types.md
                #- typing: coding/python/builtin/typing.md
                #- urllib: coding/python/builtin/urllib.md
                #- uuid: coding/python/builtin/uuid.md
                #- venv: coding/python/builtin/venv.md
                #- xml: coding/python/builtin/xml.md

          - FastAPI:
                - coding/python/fastapi/index.md
                - Parameter: coding/python/fastapi/parameter.md
                - Request Body: coding/python/fastapi/request-body.md
          - Typing:
                - coding/python/typing/index.md
          - Pickle:
                - coding/python/pickle/index.md

    - Web Dev:
          - HTML:
                - webdev/html/index.md
                - Common Elements: webdev/html/common-elements.md
                - Meta Tags: webdev/html/meta-tags.md
          - CSS:
                - webdev/css/index.md
                - Selectors: webdev/css/selectors.md
                - Common Properties: webdev/css/common-properties.md
                - Box Model: webdev/css/box-model.md
                - Structured Content: webdev/css/structured-content.md
          - Java Script:
                - webdev/javascript/index.md
                - Variables & Data Types: webdev/javascript/var-datatypes.md
                - Operators & Conditionals: webdev/javascript/operators-conditionals.md
                - Loops & Iterations: webdev/javascript/loops-iterations.md
                - Functions: webdev/javascript/functions.md
                - Classes: webdev/javascript/classes.md
                - Error Handling: webdev/javascript/error-handling.md
          - Angular:
                - webdev/angular/index.md
                - Modules: webdev/angular/modules.md
                - Components: webdev/angular/components.md
                - Directives: webdev/angular/directives.md
                - Dependency Injection: webdev/angular/dependency-injection.md
                - Testing: webdev/angular/testing.md
                - First-party Libraries: webdev/angular/angular-libraries.md

    - Go:
          - coding/golang/index.md
          - Commands: coding/golang/commands.md
          - Concepts and Data Types:
                - Data Types: coding/golang/types.md
                - Arrays & Slices: coding/golang/arrays.md
                - Maps: coding/golang/maps.md
                - Pointers: coding/golang/pointers.md
          - Loops and Conditionals:
                - If else: coding/golang/if-else.md
                - Switch: coding/golang/switch.md
                - For Loops: coding/golang/for-loops.md
                - Defer: coding/golang/defer.md
          - Functions and Structs:
                - Functions: coding/golang/functions.md
                - Structs: coding/golang/structs.md
                - Interfaces: coding/golang/interfaces.md
          #- Concurrency:
          #- Errors and Testing:

    - Java:
          - coding/java/index.md

    - BSc Study:
          - ds-study/index.md
          - Math:
                - math/index.md
                - General: math/general.md
                - Linear Algebra: math/linear-algebra.md
                - Analysis: math/analysis.md
          - Data Engineering 1:
                - RegEx: ds-study/de1/regex.md
                - Structured Data: ds-study/de1/structured.md
                - Unstructured Data: ds-study/de1/unstructured.md
                - Big Data: ds-study/de1/bigdata.md
          - Programming 2:
                - Object Oriented: ds-study/prog2/oop.md
                - Testing: ds-study/prog2/testing.md
                - Requests: ds-study/prog2/requests.md
                - Pandas: ds-study/prog2/pandas.md
                - Internet Standars: ds-study/prog2/standards.md
                - Sorting Algorithms: ds-study/prog2/sorting.md
