site_name: JohnTrunix's Brain Cache
site_author: JohnTrunix
site_description: JohnTrunix's Brain Cache, my personal go-to hub for tech-savvy personal notes and insights

site_url: https://johntrunix.github.io/brain-cache/
repo_name: JohnTrunix/brain-cache
repo_url: https://github.com/JohnTrunix/brain-cache
remote_branch: gh-pages
edit_uri: edit/main/docs/

theme:
    name: material
    #custom_dir: overrides
    language: en
    logo: assets/rocket.png
    favicon: assets/favicon.ico

    icon:
        repo: fontawesome/brands/github
        view: octicons/file-code-16

        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16

    font:
        text: Roboto
        code: Fira Code

    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-6
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-6
              name: Switch to light mode

    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.sections
        - navigation.indexes
        - navigation.top
        - navigation.footer
        - search.suggest
        - search.share
        - content.action.view
        #- content.action.edit
        - content.code.copy

extra_css:
    - assets/css/tweaks.css

extra_javascript:
    - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
    - assets/js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/JohnTrunix/
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/john-truninger/
        - icon: simple/kofi
          link: https://ko-fi.com/johntrunix
    analytics:
        provider: google
        property: G-KY2RP9BZ91
        feedback:
            title: Was this page helpful?
            ratings:
                - icon: octicons/heart-16
                  name: This page was helpful
                  data: 1
                  note: >-
                      Thanks for your feedback!
                - icon: octicons/x-16
                  name: This page could be improved
                  data: 0
                  note: >-
                      Sorry to hear that. Can you give me some suggestions for improvement?

copyright: Copyright &copy; 2023 JohnTrunix

plugins:
    - social:
          cards: !ENV [CARDS, true]
          cards_dir: assets/cards
    - tags
    - search:
          lang:
              - en
              - de

markdown_extensions:
    - attr_list
    - def_list
    - markdown.extensions.admonition
    - markdown.extensions.footnotes
    - markdown.extensions.toc:
          permalink: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
          linenums: True
          linenums_style: table
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.mark
    - pymdownx.details

nav:
    - Overview:
          - index.md
          - Ideas & Upcoming Projects: overview/ideas-upcoming-projects.md
          - Links & Resources: overview/urls-resources.md
    - Genral Notes:
          - MkDocs Material: general-notes/mkdocs-material.md
